{
 "title": "Gova Project",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "node-exporter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "uso da memória total x free x disponivel",
   "type": "timeseries",
   "description": "*node_memory_MemTotal_bytes: Essa métrica representa a quantidade total de memória RAM disponível no sistema, em bytes. Ela indica a capacidade máxima de memória do sistema.\n--------------------------------------------------\n*node_memory_MemFree_bytes: Essa métrica indica a quantidade de memória RAM livre no sistema, ou seja, a quantidade de memória que não está sendo utilizada no momento.\n--------------------------------------------------*\nnode_memory_MemAvailable_bytes: Essa métrica indica a quantidade de memória RAM disponível para processos alocarem sem causar pressão na memória. Ela leva em consideração não apenas a memória livre, mas também a memória em cache e em buffer que pode ser liberada para uso.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    { "expr": "node_memory_MemAvailable_bytes", "legendFormat": "__auto" },
    { "expr": "node_memory_MemFree_bytes", "legendFormat": "__auto" },
    { "expr": "node_memory_MemTotal_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "carga media do sistema em 1x5x15m",
   "type": "timeseries",
   "description": "Essas métricas representam a carga média do sistema nos últimos 1, 5 e 15 minutos, respectivamente. Elas podem indicar o nível de utilização do CPU, pois uma carga alta indica que o sistema está demandando mais recursos do processador.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    { "expr": "node_load1", "legendFormat": "__auto" },
    { "expr": "node_load5", "legendFormat": "__auto" },
    { "expr": "node_load15", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "uso da cpu total - modo sistema",
   "type": "timeseries",
   "description": "node_cpu_seconds_total: Essa métrica fornece o tempo total de CPU consumido em segundos. Ela pode ser usada para calcular a porcentagem de uso do CPU ao longo do tempo. Modo Sistema",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "node_cpu_seconds_total{mode=\"system\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "uso total de cpu - modo ocioso",
   "type": "timeseries",
   "description": "node_cpu_seconds_total: Essa métrica fornece o tempo total de CPU consumido em segundos. Ela pode ser usada para calcular a porcentagem de uso do CPU ao longo do tempo. Modo Ocioso",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "node_cpu_seconds_total{mode=\"idle\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "uso da cpu total - modo usuário",
   "type": "timeseries",
   "description": "node_cpu_seconds_total: Essa métrica fornece o tempo total de CPU consumido em segundos. Ela pode ser usada para calcular a porcentagem de uso do CPU ao longo do tempo. Modo usuário",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "node_cpu_seconds_total{mode=\"user\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "pethsop",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "total de clientes atendidos",
     "type": "timeseries",
     "description": "Uma métrica que indica a quantidade total de clientes atendidos",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
     "targets": [
      { "expr": "pet_shop_total_pets_served", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "qualidade do atendimento",
     "type": "timeseries",
     "description": "soma das notas  para o atendimento x quantidade de notas.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
     "targets": [
      { "expr": "pet_shop_score_count", "legendFormat": "__auto" },
      { "expr": "pet_shop_score_sum", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "clientes em espera",
     "type": "timeseries",
     "description": "Uma métrica que indica a quantidade de clientes em espera",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
     "targets": [
      { "expr": "pet_shop_pets_in_queue", "legendFormat": "__auto" }
     ]
    }
   ]
  }
 ]
}