version: '3.8'

services:
  prometheus:
    image: prom/prometheus:main
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ~/deploy/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - node-exporter
      - petshop
    networks:
      - monitoring

  node-exporter:
    image: prom/node-exporter:master
    container_name: node-exporter
    ports:
      - 9100:9100
    networks:
      - monitoring

  petshop:
    image: harbor.sflabs.com.br/processo/petshop:latest
    container_name: petshop
    ports:
      - 3000:3000
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:main-ubuntu
    container_name: grafana
    ports:
      - 80:3000
    volumes:
      - ~/deploy/grafana:/var/lib/grafana
    user: "472:472"
    networks:
      - monitoring

volumes:
  grafana_data:
  prometheus:

networks:
  monitoring:
    driver: bridge