{
 "title": "Node-Exporter",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Node_LarguraDeBanda",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "node_network_receive_bytes_total",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_network_transmit_bytes_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node_UsoDaCpu-Ocioso",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "node_cpu_seconds_total{mode=\"idle\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node_tempoDeAtividade",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "node_boot_time_seconds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Node_UsoDaMemoria",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "node_memory_MemTotal_bytes", "legendFormat": "__auto" },
    { "expr": "node_memory_Cached_bytes", "legendFormat": "__auto" },
    { "expr": "node_memory_MemFree_bytes", "legendFormat": "__auto" },
    { "expr": "node_memory_Buffers_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Node_EspaçoLivre_FileSystem",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "node_filesystem_avail_bytes", "legendFormat": "__auto" }
   ]
  }
 ]
}