{
 "title": "petshop_app",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "petshop_mediaDoScore",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "pet_shop_score_count", "legendFormat": "__auto" },
    { "expr": "pet_shop_score_sum", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Petshop overview",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "pet_shop_total_pets_served{job=\"petshop\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "pet_shop_pets_in_queue{job=\"petshop\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "petshop_petsAtendidos",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "pet_shop_total_pets_served{instance=\"petshop:3000\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Petshop_filaDeEspera ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "pet_shop_pets_in_queue{job=\"petshop\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}